### ISSUE TITLE
Transcript header typo

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/dW#102]
http://ibmtvdemo.edgesuite.net/software/im/text-versions/manage-io-performance-script.pdf?cm_mc_uid=02806715020514758523856&cm_mc_sid_50200000=1476295783

Change "DB2 ON Cloud" to "DB2 on Cloud"

**Comment by jessmantaro** [comment]
Our team doesn't have access to this pdf file. Arg. Very minor issue. Going to leave it as is.
