### ISSUE TITLE
Search Dropdowns Not Working

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/dW#107]
The search dropdowns are not standard dropdowns so they're not "clickable" (I'm a keyboard-only user using the Vimium plugin in Chrome) - see attached screenshot where the yellow labels are things that I can "click" on, but the dropdowns aren't accessible.
![screenshot-20161012195808](https://cloud.githubusercontent.com/assets/172607/19323842/807d779c-90b6-11e6-936e-7520234a6225.png)

**Comment by vabarbosa** [comment]
addressed
