### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by vabarbosa** [ibm-cds-labs/dW#110]
the following pages have broken links:

https://developer.ibm.com/clouddataservices2/2016/03/09/introducing-spark-cloudant-connector
**Big Data University** link broken

https://developer.ibm.com/clouddataservices2/2016/07/15/intro-to-apache-spark-graphframes
**Installing GraphFrames** link broken

https://developer.ibm.com/clouddataservices2/docs/spark/get-started/get-started-in-bluemix
**Precipitation Analysis** video link (step 7) broken

**Comment by jessmantaro** [comment]
All 3 fixed
