### ISSUE TITLE
Missing pages from dashDB docs>Load>Bring Your Oracle and Netezza Apps...

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/dW#116]
https://developer.ibm.com/clouddataservices2/docs/dashdb/load/bring-your-oracle-and-netezza-apps-to-dashdb-with-database-conversion-workbench-dcw/

Links in the bullets under "The two primary ground-to-cloud migration paths supported by DCW are:" are broken since the pages don't exist.

Links under "Conversion Guides" are also broken.

**Comment by jessmantaro** [comment]
Fixed. pages actually do still exist, but names and locations had changed
