### ISSUE TITLE
Links to BigInsights GitHub are weird 

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/dW#119]
On the 2 links under "Get Started" under the video, if you click on them it opens GitHub a new window, and when you go back to the original window there's a dotted line box around the link that won't go away.

True on both of these sites: 

https://developer.ibm.com/clouddataservices2/docs/biginsights/enterprise-plan/sample-scripts/

https://developer.ibm.com/clouddataservices2/docs/biginsights/basic-plan/try-github-examples/

**Comment by jessmantaro** [comment]
fixed.
