### ISSUE TITLE
Style definition lists

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#128]
These are handy for FAQs and currently have no styling. We need at least the `<dt>` element to be bold. Probably good to have spacing between elements too. There's a definition list on this page: https://developer.ibm.com/clouddataservices2/docs/lift/faqs/ and this page: https://developer.ibm.com/clouddataservices2/docs/dashdb/load/manage-data-with-dashdb-support-tools/

**Comment by vabarbosa** [comment]
addressed
