### ISSUE TITLE
code in `<pre><code>` tags too wide

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#133]
See this post: https://developer.ibm.com/clouddataservices2/2016/03/31/multiplying-microservices/ and search for _Counting distinct values_ see code for line that goes far right. Compare to styling on our old site, which wraps these snippets: https://developer.ibm.com/clouddataservices/2016/03/31/multiplying-microservices/ 

We don't use `<pre><code>` very often, but sometimes must, so good to have this style set.

**Comment by vabarbosa** [comment]
addressed
