### ISSUE TITLE
Feature Request: Make Scroll Bar visible on Code Snippets

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/dW#142]
Code snippets in blog posts look like they are cut off to the naked eye but only when you hover over them you realize they have a scroll bar. Let's: Make the scroll bar visible and/or make the blog a bit wider to accommodate longer code snippets OR follow Githubs lead and give a background to code snippets and restrict them to one line so the user experience transfers more cleanly. This will feel more familiar to developers who are used to the way Github handles code snippets with markdown.

Example: 

Snippet should be:

```
curl -X POST -H "Content-Type: application/json" 'https://sevendays:password@sevendays.cloudant.com/students' -d '{"name": "Janet Doe", "modules": [{"name": "Calculus 101", "score": 87}]}'
```

On Dev Advo blog it shows as:
![screen shot 2016-10-24 at 1 48 34 pm](https://cloud.githubusercontent.com/assets/4404929/19657076/9c0852e6-99f0-11e6-9247-16978ac592eb.png)

On Github it shows as:
![screen shot 2016-10-25 at 12 35 38 pm](https://cloud.githubusercontent.com/assets/4404929/19695042/a11fe4aa-9aaf-11e6-8fc3-6d64a2d84ddb.png)

**Comment by mikebroberg** [comment]
Fixed our SyntaxHighlighter with our own custom plugin with help from Raj and Va. Thanks, guys!

![screen shot 2016-12-07 at 3 04 54 pm](https://cloud.githubusercontent.com/assets/3170980/20984503/8c4d0cf0-bc8e-11e6-9a35-82be902ce6c8.png)
