### ISSUE TITLE
Marvin's author points to wrong page

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#146]
Links to my page (Jess) for some reason. May try deleting me. See if that fixes it.

**Comment by jessmantaro** [comment]
To reproduce: Click **Blog**, then click the advocate icons. Within the Advocates overlay that appears, click on Marvin the robot. Jess Mantaro's profile appears instead of Marvin's. Have tried deleting each users, but prob persists. DB mismatch?

**Comment by oeschger** [comment]
Hi Jess - This is another one that is outside of our purview (I think) because the site/theme was developed by an outside agency. Hope you've found some solution here. 

~ Ian

**Comment by vabarbosa** [comment]
fixed! woohoo!
