### ISSUE TITLE
Blog page: In Chrome, advocates list overlay appears too far left, behind main nav

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#147]
![screen shot 2016-10-28 at 13 11 40](https://cloud.githubusercontent.com/assets/12279008/19807752/9694cf04-9cef-11e6-86ef-408281afc422.png)

**Comment by vabarbosa** [comment]
issue is not with chrome but more specifically with the responsiveness of the devadvo tray. changing browser window size surfaces the issue when width is between 1251px - 1638px.
it has been addressed.
