### ISSUE TITLE
Use metadata instead of Admin permissions to identify dev advocates

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#150]

**Comment by vabarbosa** [comment]
change has been made. a new field, "Developer Advocate" has been added to the user profile edit page. enable this field for users who are developer advocates and should be listed in under the Developer Advocacy list on the site.

fyi, in wordpress to query against this "Developer Advocate" metadata use:

```
$args = array(
  'meta_query' => array(
    array(
      'key' => 'is_dev_advo',
      'value' => 'on'
    )
  )
);
$devadvos = new WP_User_Query($args);
```
