### ISSUE TITLE
Showcases page - Deploy2Bluemix button

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/dW#152]
It's not rendering for Mark Watson's Location Tracker app (bottom example):

![screen shot 2016-11-01 at 3 14 36 pm](https://cloud.githubusercontent.com/assets/3170980/19903749/1d73c47c-a046-11e6-8c29-55dbfaa09ade.png)

**Comment by jessmantaro** [comment]
Fixed!
