### ISSUE TITLE
Styling of WP right-aligned images with captions

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/dW#153]
Using the built in options to add media with captions produced this layout:

![screen shot 2016-11-01 at 5 43 40 pm](https://cloud.githubusercontent.com/assets/3170980/19908727/e50d2f50-a05a-11e6-89d7-b580fb4b2704.png)

Is there a way to change this so there's more padding on the left side, and less extra space along the bottom? Thanks!

**Comment by vabarbosa** [comment]
addressed
