### ISSUE TITLE
footer hidden under sidenav, globally

### ISSUE THREAD

**Issue by bradnoble** [ibm-cds-labs/dW#154]
https://www.dropbox.com/s/cuii6cdpal9odc5/Screenshot%202016-11-02%2010.39.13.png?dl=0

**Comment by mikebroberg** [comment]
I noticed that this morning, but then refreshed my browser and everything was fine. It seems fine and stable now. I assumed it was maybe a temporary problem with developerWorks and not our styling? I've never otherwise seen this effect.

**Comment by vabarbosa** [comment]
i am not seeing this issue either. @bradnoble show me your machine if you continue to see the problem.
