### ISSUE TITLE
Move old subscribers to new DB

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#155]
Users who previously subscribed for email notifications aren't getting latest posts. Can we port old users into new WP DB?

**Comment by jessmantaro** [comment]
To access old list: go to clouddataservicesold WP dashboard. Choose **Jetpack > Site Stats**. Scroll to bottom of page. In **Subscriptions** section, click **Blog** link. List appears.

Did some research on this. (see https://jetpack.com/2012/01/17/how-to-view-your-email-subscribers/) Plugin is limited. We can't delete anyone off this list and may not be able to port them over. When I try to download a csv file, I'm prompted to sign into wp.com - web service, where I guess they are stored. My creds don't work. Need DevWorks master?

**Comment by isc-rsingh** [comment]
I can't even see blog subscribers.
I doubt we can port over subscribers. It seems like that would be a privacy issue since someone could use that feature to just load up a database of email addresses and spam them. Maybe Ian can do some database-level hack?

**Comment by jessmantaro** [comment]
Broberg and I notified current subscribers and manually entered each to sign up again. Did all we could! Hopefully most confirm and continue to follow.
