### ISSUE TITLE
Search (again) returns results from DataSciX namespace

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/dW#158]
Glynn fixed this once before on our old site, but the problem is back after moving to the new design.

![screen shot 2016-11-07 at 10 29 28 am](https://cloud.githubusercontent.com/assets/3170980/20063450/26c7fe24-a4d5-11e6-8dc6-9812a1cf040a.png)

![screen shot 2016-11-07 at 10 29 42 am](https://cloud.githubusercontent.com/assets/3170980/20063449/26bb2140-a4d5-11e6-8a16-f0780af6e1b7.png)

**Comment by vabarbosa** [comment]
addressed
