### ISSUE TITLE
Kerning for <vowel> + "e"

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/dW#161]
Words with vowels preceding an "e" in our blog have weird kerning:

![screen shot 2016-11-16 at 11 07 19 am](https://cloud.githubusercontent.com/assets/3170980/20354900/8fc09034-abed-11e6-8f8f-fa8aca893a5d.png)

![screen shot 2016-11-16 at 11 11 08 am](https://cloud.githubusercontent.com/assets/3170980/20354901/8fc89400-abed-11e6-8086-89054eb3a71c.png)

**Comment by vabarbosa** [comment]
addressed
