### ISSUE TITLE
We must format individual event pages

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#164]
Developer.ibm.com scrapes our event list, but doesn't grab the registration field. That site also links back to our individual event pages, which have no formatting, since we weren't exposing them.

We need to change the indiv. event pages to:
- show attendees instead of author
- show the Register button
- look better. Info is all jumbled together. Needs better layout.

Note from Lou:

Hi Jessica.  All events appear on this page:
https://developer.ibm.com/all-events/

When you click on the link for ConFoo Vancouver, it opens this page:
https://developer.ibm.com/clouddataservices/events/confoo-vancouver/
There's no registration link on that page. It would be helpful to add one to the abstract.

And also with DevRelCon London:
https://developer.ibm.com/clouddataservices/events/devrelcon-london/
(no registration link).

I see categories for both events have been added.  Thanks for doing that.

Please add the registration links (or event links) to the event entries in word press for these 2 and all events
you create in the future. That makes it easier for users to find the event pages.

Thank you!

**Comment by jessmantaro** [comment]
I did a quick & dirty fix, by making events display using default page template instead of blog post format (thus got rid of irrelevant "author" field). But layout could be vastly improved. Plus we need attendees and register button

**Comment by vabarbosa** [comment]
@jessmantaro i have created a new page for single events and change the settings to use the new page. let me know if there are any other changes you want made on this new page
