### ISSUE TITLE
Suggestion for Typography Change @ Blog

### ISSUE THREAD

**Issue by yumeforever** [ibm-cds-labs/dW#165]
Hello guys, 
I was on the website yesterday and I was reading trough some articles and found the Helvetica Light used for the text kind of difficult for long reading, also the links with very bright green/blue was kind of unaccessible.
I would like to make a suggestion for a quick and small change to those:
1. Having the Helvetica Regular instead of Light
2. A Darker color version for the links or maybe an alternative one. 

Current:
![screen shot 2017-01-23 at 13 54 03](https://cloud.githubusercontent.com/assets/3612533/22241524/077c97cc-e220-11e6-99f2-b379c5dd6d9d.png)

Suggestion (with Helvetica Light and darker Acqua - the color can be even darker or different)
![screen shot 2017-01-23 at 13 53 51](https://cloud.githubusercontent.com/assets/3612533/22241553/21169b7e-e220-11e6-97fd-9fed12885525.png)

Cheers,
Morgana D'Almeida
IBM Design Studio Böblingen, Germany.

**Comment by isc-rsingh** [comment]
Thanks for the input @yumeforever. We've moved our blog to https://medium.com/ibm-watson-data-lab so the typography is a lot better now.
