### ISSUE TITLE
Garbage appending to URL after clicking links to filtered search

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#3]
On Get Started page, when you click a link under "What will you build?   Find articles..."   It opens a pre-filtered search in the ToDos page. But then if you click to other pages filter info hangs around  in the address bar (appended to each page address) and messes up any future "What will you build" results.

**Comment by jessmantaro** [comment]
For example click the mobile link: https://developer.ibm.com/clouddataservices/how-tos/#?&filter=[{%22key%22%3A%22topic%22%2C%22value%22%3A%22Mobile%22}]
then say you want to leave the HowTos screen, so you click the Blog menu item. Blog opens but URL in the address bar is: https://developer.ibm.com/clouddataservices/blog/?&filter=[{%22key%22%3A%22topic%22%2C%22value%22%3A%22Mobile%22}]
Then, if you return to the Get Stared page, search parameters persist and are appended to Get Started address: https://developer.ibm.com/clouddataservices/get-started/?filter=%22key%22%3A%22topic%22%2C%22value%22%3A%22Mobile%22
Then if you click another "how to's" topic, say the one on warehousing, mobile setting from last search remains and so desired warehousing filter not applied. URL becomes:
https://developer.ibm.com/clouddataservices/how-tos/#?&filter=[{%22key%22%3A%22topic%22%2C%22value%22%3A%22Data%20Warehousing%22}]&filter=%22key%22%3A%22topic%22%2C%22value%22%3A%22Mobile%22

and search opens to its "home" state.

**Comment by glynnbird** [comment]
This looks like a problem in the Developer Center code. If you look at the markup that is generated, the HTML for the menu bar which contains the link to "Blog" is:

```
<li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31"><a href="https://developer.ibm.com/clouddataservices/blog/?&amp;filter=%5B%7B%22key%22%3A%22topic%22%2C%22value%22%3A%22Analytics%22%7D%5D">Blog</a></li>
```

when it should be:

```
<li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31"><a href="https://developer.ibm.com/clouddataservices/blog/">Blog</a></li>
```

This markup is not generated by the search engine, it's generated in WordPress markup somewhere.

**Comment by glynnbird** [comment]
This seems to be a "feature" of the Dev Center version of WordPress. Possibly something to do with the SEO plugin. It happens on other people's Dev Centers but  not vanilla WordPress

**Comment by isc-rsingh** [comment]
fixed by @glynnbird by changing #? to #!
