### ISSUE TITLE
Learning Center left nav parent items don't collapse

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#53]
In the learning center, our collapsable left nav menu doesn't collapse. 

See staging server: https://nextstage.torolab.ibm.com/clouddataservices/docs/ahome/

Soon we'll have 3 levels
Service name  > subfolder > topic

We'd like:
- only the open topic's subfolder to be expanded
- other subfolders within same service visible, but collapsed
- Other services collapsed entirely

**Comment by isc-rsingh** [comment]
fixed in CSS
