### ISSUE TITLE
Show Events on Author Page

### ISSUE THREAD

**Issue by bradley-holt** [ibm-cds-labs/dW#61]
It would be great if the upcoming events which a person is attending showed up on that person's author page.

**Comment by isc-rsingh** [comment]
great idea! difficult to implement...

**Comment by bradley-holt** [comment]
@rajrsingh Maybe we should rethink how author pages are implemented. For example, maybe we create a new "advocate" page (one per advocate) on which we can aggregate various pieces of content related to that person (rather than trying to force this into the WP author page).
