### ISSUE TITLE
Blog: Text cut off in Recent Posts for author

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/dW#75]
1. Go to blog: https://developer.ibm.com/clouddataservices2/blog/#
2. Find an article by Patrick
3. Click ptitzler
4. Note some text is cut off under Recent Posts

**Comment by jessmantaro** [comment]
This box limited to a set number of lines. Patrick's happens to cut off mid-description, but readers can click the Learn More button, so I'm going to close this out.
