### ISSUE TITLE
Images too wide

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/dW#76]
The images in https://developer.ibm.com/clouddataservices2/2015/12/03/get-in-line-an-intro-to-queues-and-pubsub/ are wider than the content since the content pane is so much narrower in the new design.  The code samples also scroll horizontally where previously they displayed without needing to scroll

**Comment by lornajane** [comment]
Also https://developer.ibm.com/clouddataservices2/2015/11/11/scale-a-web-app-with-microservices-and-message-hub/

**Comment by lornajane** [comment]
Most code samples now scroll horizontally but in this post https://developer.ibm.com/clouddataservices2/2016/03/31/multiplying-microservices/ the code samples are too wide like the images

**Comment by jessmantaro** [comment]
Marcus had readjusted image width. These are wider than the text, but not by much, so I think that's ok. Code bleeding right is a problem with simple `<pre><code>` tags. Creating a separate style issue for that.
