### ISSUE TITLE
Showcase Landing Pages - Github Data

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/dW#82]
The pages linked from https://developer.ibm.com/clouddataservices2/showcases/ have a section at the top with github data and the Github-Info Categories-list has some messy alignment.

![screen shot 2016-10-12 at 2 33 10 pm](https://cloud.githubusercontent.com/assets/4404929/19322953/efbab27e-9088-11e6-9168-e7999867d6e4.png)

Example url: https://developer.ibm.com/clouddataservices2/simple-data-pipe/

**Comment by vabarbosa** [comment]
addressed
