### ISSUE TITLE
How To bulleted list formatting

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/dW#84]
In Data Connect How Tos (for example, https://developer.ibm.com/clouddataservices2/docs/dataconnect/how-to/load-data-for-analytics/), there are lists of specific how to videos at the bottom.  It makes a > symbol to highlight which one you're currently on, but that symbol overlaps with the bullets and looks weird.

**Comment by terichadbourne** [comment]
might be same as issue 78

**Comment by vabarbosa** [comment]
duplicate of #78
