### ISSUE TITLE
Offline-first: Hyper links not clickable however works if new tab or copy paste url

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/dW#85]
URL is https://developer.ibm.com/clouddataservices/location-tracker/ and it works otherwise. Just clicking the link from the page won't do anything in FF.

**Comment by chetnawarade** [comment]
This issue belongs to offline-first page https://developer.ibm.com/clouddataservices2/offline-first/

**Comment by jessmantaro** [comment]
Fixed. Missing destination file and missing <p> tag were the culprits
