### ISSUE TITLE
Showcases page - Email Subscription link doesn't validate

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/dW#88]
The email submission link for sign-up at the bottom of the showcases page doesn't validate for email address. I was able to add text that was not email@address.com format (for example something that's just "askldfasjdk" or "test@bademail") and the form submitted anyway. Also when I submitted my email, I was pushed back to the top of the page, instead of anchored at the email section so that I can see my submission went through. 

![screen shot 2016-10-12 at 2 36 12 pm](https://cloud.githubusercontent.com/assets/4404929/19323076/775651c0-9089-11e6-89d6-51aaa86e6191.png)

https://developer.ibm.com/clouddataservices2/showcases/

**Comment by jessmantaro** [comment]
We can:
-remove this form, as we did on the home page
-or replace with subscription widget

**Comment by vabarbosa** [comment]
removed
