### ISSUE TITLE
Blog: Table/code formatting in Reddit/R blog

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/dW#89]
1. Go to https://developer.ibm.com/clouddataservices2/2016/08/15/reddit-sentiment-analysis-in-sparkr-and-couchdb/
2. Search for "Output looks like"
3. Note the formatting of the following code, especially the table (the text "```" denoting the end of the code snippet is also present)

**Comment by jessmantaro** [comment]
Fixed. Code too wide and no need to copy it, so replaced with screen shot
