### ISSUE TITLE
QA on mobile devices

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/dW#93]

**Comment by mmcelaney** [comment]
FYI - I already checked on mobile (slightly) and submitted a mobile issue in issue #95

**Comment by jessmantaro** [comment]
Checked on ipad and iphone. Looks pretty good predictable wrapping in spots, but menu adjusts nicely to icons and all seems to work well. Issue 95 resolved also - we ended up removing that email form - was the wrong widget.
