### ISSUE TITLE
Showcases page - MOBILE - Email Subscription link field tiny

### ISSUE THREAD

**Issue by mmcelaney** [ibm-cds-labs/dW#95]
On MOBILE the email submission link for sign-up at the bottom of the showcases page is tiny, while still clickable it doesn't appear usable.

![img_1298](https://cloud.githubusercontent.com/assets/4404929/19323410/c2a5eab8-908a-11e6-8658-316b521b3edd.PNG)

https://developer.ibm.com/clouddataservices2/showcases/

**Comment by mmcelaney** [comment]
@jessmantaro will QA for more mobile bugs under #93

**Comment by vabarbosa** [comment]
addressed
