### ISSUE TITLE
Apache Spark Analytics: "Tutorial" hyperlink does NOT move focus to Tutorials

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/dW#97]
instead page refreshes to the top of the page. Current link is https://developer.ibm.com/clouddataservices2/apache-spark-analytics/ should be https://developer.ibm.com/clouddataservices2/apache-spark-analytics#Tutorial something on that line.

**Comment by jessmantaro** [comment]
Fixed by removing link (list of tutes follows inline below that mention)
