### ISSUE TITLE
Epic 404 on SETI Data post

### ISSUE THREAD

**Issue by lornajane** [ibm-cds-labs/dW#98]
https://developer.ibm.com/clouddataservices2/2016/09/29/seti-data-on-ibm-cloud/ doesn't exist, but the search results points me to https://developer.ibm.com/clouddataservices/2016/09/29/seti-data-on-ibm-cloud/

**Comment by lornajane** [comment]
Also https://developer.ibm.com/clouddataservices2/2016/10/05/7-databases-7-days-postgresql/ - is it the new posts that don't have rewrites yet?

**Comment by jessmantaro** [comment]
Yes - it was manually-copied posts that were assigned different slugs. Fixed all that differed. Great catch!
